#creating databse

CREATE DATABASE customerdb;
USE customerdb;

# check the imported database from python
SELECT *
FROM customers
limit 10;

 # 1) What is the total revenue generated by male vs. female customers?
 
 SELECT gender, sum(purchase_amount) as revenue
 FROM customers
 GROUP BY gender;
 
 # 2) find the total revenue for each age groups

WITH age_type AS ( SELECT purchase_amount, CASE
WHEN age BETWEEN 1  AND 18 THEN 'children'
WHEN age BETWEEN 19 AND 30 THEN 'adult'
WHEN age BETWEEN 31 AND 49 THEN 'senior adult'
ELSE 'elder' END AS age_group
FROM customers)

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM age_type
GROUP BY age_group;
 
# 3) Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, purchase_amount, discount_applied
FROM customers
where discount_applied = "yes"
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customers);

# 4) Which are the top 5 products with the highest average review rating?

SELECT item_purchased, avg(review_rating) as avg_review_rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
limit 5;

 # 5) Compare the average Purchase Amounts between Standard and Express Shipping. 
 
SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN ("express", "standard")
GROUP BY shipping_type;

 # 6) Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
 
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
AVG(purchase_amount) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

# 7) Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
round(100 *sum(CASE 
WHEN discount_applied = "yes" THEN 1 
ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 

# 8) Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS ( 
SELECT customer_id, previous_purchases, CASE 
WHEN previous_purchases = 1 THEN 'new'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
ELSE 'loyal' END AS customer_segment
FROM customers)

SELECT customer_segment, count(*) AS num_of_customers
FROM customer_type
GROUP BY customer_segment;

# 9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, count(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

# 10) what are the top 3 most prefered payment menthods used by the customers?

SELECT payment_method, count(customer_id) AS customer_used
FROM customers 
GROUP BY payment_method
ORDER BY customer_used DESC
LIMIT 3;